development:
    :address: smtp.gmail.com
    :port: 587
    :authentication: plain
    :user_name: thekkarol@gmail.com
    :password: prettyWis3#
    :enable_starttls_auto: true
production:
    :address: smtp.gmail.com
    :port: 587
    :authentication: plain
    :user_name: thekkarol@gmail.com
    :password: prettyWis3#
    :enable_starttls_auto: true